[package]
name = "sigma-ssg"
version = "0.1.0"
authors = ["Denis Onder <denis_onder@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
